## Secret resource is not uploaded on GitHub
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-kafka-producer
  namespace: amazon-music-review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-kafka-producer
  template:
    metadata:
      labels:
        app: telegram-kafka-producer
    spec:
      containers:
        - name: telegram-kafka-producer
          image: telegram-kafka-producer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-credentials
                  key: telegram-bot-token
            - name: TELEGRAM_BOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-credentials
                  key: telegram-bot-username
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "amazon-music-review-kafka-service.amazon-music-review.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "social-media-topic"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: telegram-kafka-producer-service
  namespace: amazon-music-review
spec:
  selector:
    app: telegram-kafka-producer
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
