apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2 # Explicitly use the gp2 storage class
  resources:
    requests:
      storage: 10Gi
