apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: amazon-music-review-cluster
  region: ap-southeast-1

iam:
  withOIDC: true
  serviceRoleARN: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/amazon-music-review-eks-cluster-role"

nodeGroups:
  - name: ng-1
    instanceType: t3.medium # Choose an appropriate instance type
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    iam:
      instanceRoleARN: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/amazon-music-review-eks-node-role"
    ssh:
      allow: true # Enable SSH access for debugging
      publicKeyName: ${AWS_EC2_KEY} # Replace with your EC2 key pair name

# Add CloudWatch logging
cloudWatch:
  clusterLogging:
    enableTypes:
      ["api", "audit", "authenticator", "controllerManager", "scheduler"]
