apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: amazon-music-review-cluster
  region: ap-southeast-1

iam:
  withOIDC: true
  serviceRoleARN: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/amazon-music-review-eks-cluster-role"

nodeGroups:
  - name: ng-1
    instanceType: t3.medium # 2vCPU, 4GB RAM
    desiredCapacity: 3
    minSize: 1
    maxSize: 4
    iam:
      instanceRoleARN: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/amazon-music-review-eks-node-role"
    ssh:
      allow: true # Enable SSH access for debugging
      publicKeyName: ${AWS_EC2_KEY} # Replace with your EC2 key pair name

