apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: amazon-music-review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: confluentinc/cp-kafka-connect:7.5.0
          ports:
            - containerPort: 8083
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "amazon-music-review-kafka-service:9092"
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_GROUP_ID
              value: "kafka-connect-group"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: "connect-configs"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: "connect-offsets"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: "connect-status"
            - name: CONNECT_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_INTERNAL_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_INTERNAL_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONNECT_PLUGIN_PATH
              value: "/usr/share/java,/usr/share/confluent-hub-components"
          volumeMounts:
            - name: avro-data
              mountPath: /app/data
      initContainers:
        - name: install-plugins
          image: confluentinc/cp-kafka-connect:7.5.0
          command:
            - /bin/sh
            - -c
            - |
              confluent-hub install --no-prompt jcustenborder/kafka-connect-spooldir:2.0.65
          volumeMounts:
            - name: connect-plugins
              mountPath: /usr/share/confluent-hub-components
      volumes:
        - name: avro-data
          hostPath:
            path: /path/to/your/avro/files/on/macos
            type: Directory
        - name: connect-plugins
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-service
  namespace: amazon-music-review
spec:
  selector:
    app: kafka-connect
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
