apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-root
  namespace: jenkins
spec:
  ingressClassName: nginx
  rules:
    - host: jenkins.example.com # You can use a made-up hostname for testing
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  number: 8080
