apiVersion: v1
kind: Service
metadata:
  name: amazon-music-review-kafka-service
  namespace: amazon-music-review-kafka
spec:
  selector:
    app: amazon-music-review-kafka
  ports:
    - port: 9092
      targetPort: 9092
      name: plaintext
    - port: 9093
      targetPort: 9093
      name: controller
  type: ClusterIP
