apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: amazon-music-review-kafka
  namespace: amazon-music-review
spec:
  serviceName: "${KAFKA_SERVICE_NAME}"
  replicas: 1
  selector:
    matchLabels:
      app: amazon-music-review-kafka
  template:
    metadata:
      labels:
        app: amazon-music-review-kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:4.0.0
          ports:
            - containerPort: 9092
              name: plaintext
            - containerPort: 9093
              name: controller
          volumeMounts:
            - name: kafka-config
              mountPath: /opt/kafka/config/kraft/server.properties
              subPath: server.properties
            - name: kafka-data
              mountPath: /var/lib/kafka/data
            - name: format-disk
              mountPath: /tmp/format
          envFrom:
            - configMapRef:
                name: amazon-music-review-env
          env:
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: amazon-music-review-env
                  key: KAFKA_CLUSTER_ID
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - /bin/bash
            - -c
            - |
              # Replace env variables in server.properties
              envsubst < /opt/kafka/config/kraft/server.properties > /tmp/server.properties.tmp
              cp /tmp/server.properties.tmp /opt/kafka/config/kraft/server.properties
              
              # Debugging info
              echo "Starting Kafka container..."
              echo "CLUSTER_ID=$CLUSTER_ID"
              echo "KAFKA_SERVICE_NAME=$KAFKA_SERVICE_NAME"
              echo "KAFKA_PLAINTEXT_PORT=$KAFKA_PLAINTEXT_PORT"
              echo "KAFKA_CONTROLLER_PORT=$KAFKA_CONTROLLER_PORT"
              echo "Config path check:"
              ls -la /opt/kafka/config/kraft/
              echo "Contents of config file:"
              cat /opt/kafka/config/kraft/server.properties

              if [ ! -f /tmp/format/formatted ]; then
                # Format the storage
                echo "Formatting Kafka storage directory..."
                /opt/kafka/bin/kafka-storage.sh format -t $CLUSTER_ID -c /opt/kafka/config/kraft/server.properties
                touch /tmp/format/formatted
              fi

              # Set up log redirections
              exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties > /tmp/kafka.stdout.log 2> /tmp/kafka.stderr.log
      volumes:
        - name: kafka-config
          configMap:
            name: amazon-music-review-kafka-config
        - name: kafka-data
          persistentVolumeClaim:
            claimName: amazon-music-review-kafka-data
        - name: format-disk
          emptyDir: {}
