apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: amazon-music-review-kafka
  namespace: amazon-music-review
spec:
  serviceName: "amazon-music-review-kafka-service"
  replicas: 1
  selector:
    matchLabels:
      app: amazon-music-review-kafka
  template:
    metadata:
      labels:
        app: amazon-music-review-kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:4.0.0
          ports:
            - containerPort: 9092
              name: plaintext
          env:
            - name: BITNAMI_DEBUG
              value: "true"
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://amazon-music-review-kafka-service:9092"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: amazon-music-review-kafka-data
