apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: amazon-music-review-kafka-data
  namespace: amazon-music-review-kafka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 10Gi
