apiVersion: v1
kind: ConfigMap
metadata:
  name: amazon-music-review-filepulse-config
  namespace: amazon-music-review
data:
  filepulse-connector.json: |
    {
      "name": "music-review-filepulse-source",
      "config": {
        "connector.class": "io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector",
        "fs.scan.directory.path": "/app/data",
        "fs.scan.filters": "io.streamthoughts.kafka.connect.filepulse.scanner.local.filter.RegexFileListFilter",
        "fs.scan.filters.regex.pattern": ".*\\.avro$",
        "fs.scan.interval.ms": "10000",
        "fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.clean.MoveCleanupPolicy",
        "fs.cleanup.policy.move.directory.path": "/app/data/processed",
        "tasks.reader.class": "io.streamthoughts.kafka.connect.filepulse.reader.AvroFileInputReader",
        "tasks.max": "1",
        "topic": "music-reviews-topic",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": "false"
      }
    }
