apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-music-review-kafka-connect
  namespace: amazon-music-review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazon-music-review-kafka-connect
  template:
    metadata:
      labels:
        app: amazon-music-review-kafka-connect
    spec:
      initContainers:
        - name: init-kafka-connect
          image: busybox
          command:
            [
              "sh",
              "-c",
              "mkdir -p /etc/kafka-connect/secrets /etc/kafka-connect/jars /app/data/processed /app/data/error /usr/share/filepulse",
            ]
          volumeMounts:
            - name: kafka-connect-config
              mountPath: /etc/kafka-connect
            - name: kafka-connect-data
              mountPath: /app/data
            - name: plugins-dir
              mountPath: /usr/share/filepulse
      containers:
        - name: kafka-connect
          image: confluentinc/cp-kafka-connect:latest
          ports:
            - containerPort: 8083
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - name: kafka-connect-config
              mountPath: /etc/kafka-connect
            - name: filepulse-config
              mountPath: /etc/kafka-connect/filepulse
            - name: kafka-connect-data
              mountPath: /app/data
            - name: plugins-dir
              mountPath: /usr/share/confluent-hub-components
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "amazon-music-review-kafka-service:9092"
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_GROUP_ID
              value: "connect-cluster"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: "connect-configs"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: "connect-offsets"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: "connect-status"
            - name: CONNECT_KEY_CONVERTER
              value: "org.apache.kafka.connect.storage.StringConverter"
            - name: CONNECT_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
              value: "false"
            - name: CONNECT_INTERNAL_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_INTERNAL_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONNECT_PLUGIN_PATH
              value: "/usr/share/java,/usr/share/confluent-hub-components"
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - |
                    # Wait for Kafka Connect to be up
                    echo "Waiting for Kafka Connect to start..."

                    # Download and install File Pulse connector
                    cd /tmp
                    curl -L https://github.com/streamthoughts/kafka-connect-file-pulse/releases/download/v2.9.0/streamthoughts-kafka-connect-file-pulse-2.9.0.zip -o file-pulse.zip
                    unzip -o file-pulse.zip
                    mkdir -p /usr/share/confluent-hub-components/filepulse
                    cp -r /tmp/lib/* /usr/share/confluent-hub-components/filepulse/

                    # Wait for Kafka Connect API to be available
                    COUNTER=0
                    while ! curl -s http://localhost:8083/connectors; do
                      echo "Waiting for Kafka Connect REST API..."
                      sleep 5
                      COUNTER=$((COUNTER+1))
                      if [ $COUNTER -gt 10 ]; then
                        echo "Timed out waiting for Kafka Connect REST API"
                        exit 1
                      fi
                    done

                    # Create necessary directories
                    mkdir -p /app/data/processed /app/data/error

                    # Deploy the connector configuration
                    echo "Deploying File Pulse connector configuration..."
                    sleep 5
                    curl -X POST \
                      -H "Content-Type: application/json" \
                      --data @/etc/kafka-connect/filepulse/filepulse-connector.json \
                      http://localhost:8083/connectors || echo "Failed to deploy connector, will retry later"
      volumes:
        - name: kafka-connect-config
          configMap:
            name: amazon-music-review-kafka-connect-config
        - name: filepulse-config
          configMap:
            name: amazon-music-review-filepulse-config
        - name: kafka-connect-data
          persistentVolumeClaim:
            claimName: amazon-music-review-kafka-connect-data
        - name: plugins-dir
          emptyDir: {}
