apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-music-review-kafka-connect
  namespace: amazon-music-review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazon-music-review-kafka-connect
  template:
    metadata:
      labels:
        app: amazon-music-review-kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: confluentinc/cp-kafka-connect:latest
          ports:
            - containerPort: 8083
          volumeMounts:
            - name: kafka-connect-config
              mountPath: /etc/kafka-connect/
            - name: filepulse-config
              mountPath: /etc/kafka-connect/filepulse/
            - name: kafka-connect-data
              mountPath: /app/data
            - name: plugins-dir
              mountPath: /usr/share/confluent-hub-components
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "amazon-music-review-kafka-service:9092"
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_GROUP_ID
              value: "connect-cluster"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: "connect-configs"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: "connect-offsets"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: "connect-status"
            - name: CONNECT_KEY_CONVERTER
              value: "org.apache.kafka.connect.storage.StringConverter"
            - name: CONNECT_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
              value: "false"
            - name: CONNECT_INTERNAL_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_INTERNAL_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CONNECT_PLUGIN_PATH
              value: "/usr/share/java,/usr/share/confluent-hub-components,/usr/share/filestream-connectors,/usr/share/filepulse"
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - |
                    # Create directories
                    mkdir -p /app/data/processed /app/data/error /usr/share/filepulse
                    
                    # Download and install File Pulse connector
                    curl -L https://github.com/streamthoughts/kafka-connect-file-pulse/releases/download/v2.9.0/streamthoughts-kafka-connect-file-pulse-2.9.0.zip -o /tmp/file-pulse.zip
                    unzip /tmp/file-pulse.zip -d /tmp/file-pulse
                    cp -r /tmp/file-pulse/lib/* /usr/share/filepulse/
                    
                    # Wait for Kafka Connect to be up
                    echo "Waiting for Kafka Connect to start..."
                    until curl -s http://localhost:8083/connectors >/dev/null; do
                      sleep 2
                    done
                    
                    # Deploy the connector configuration
                    echo "Deploying File Pulse connector configuration..."
                    sleep 10
                    curl -X POST \
                      -H "Content-Type: application/json" \
                      --data @/etc/kafka-connect/filepulse/filepulse-connector.json \
                      http://localhost:8083/connectors || echo "Failed to deploy connector, will retry later"
      volumes:
        - name: kafka-connect-config
          configMap:
            name: amazon-music-review-kafka-connect-config
        - name: filepulse-config
          configMap:
            name: amazon-music-review-filepulse-config
        - name: kafka-connect-data
          persistentVolumeClaim:
            claimName: amazon-music-review-kafka-connect-data
        - name: plugins-dir
          emptyDir: {}
