apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-creation
  namespace: kafka-ns
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: kafka-topic-creator
          image: bitnami/kafka:4.0.0
          command:
            - /bin/bash
            - -c
            - |
              # Wait for Kafka to be fully available
              echo "Waiting for Kafka to be ready..."
              until kafka-topics.sh --bootstrap-server bitnami-kafka-0.bitnami-kafka-headless.kafka-ns.svc.cluster.local:9092 --list; do
                echo "Kafka not yet ready, waiting..."
                sleep 10
              done

              # Create required topics
              echo "Creating topics..."
              TOPICS=("social-media-topic" "user-sentiment-topic" "music-recommendation-topic")
              for TOPIC in "${TOPICS[@]}"; do
                kafka-topics.sh --create --if-not-exists --topic "$TOPIC" \
                  --bootstrap-server bitnami-kafka-0.bitnami-kafka-headless.kafka-ns.svc.cluster.local:9092 \
                  --replication-factor 1 --partitions 3
                echo "Created/verified topic: $TOPIC"
              done

              echo "Topic creation complete!"
      restartPolicy: OnFailure
