apiVersion: v1
kind: Service
metadata:
  name: bitnami-kafka-service
  namespace: kafka-ns
spec:
  selector:
    app: bitnami-kafka
  ports:
    - port: 9092
      targetPort: 9092
      name: plaintext
    - port: 9093
      targetPort: 9093
      name: controller
  type: ClusterIP
