apiVersion: v1
kind: ConfigMap
metadata:
  name: bitnami-kafka-config
  namespace: kafka-ns
data:
  init-kafka.sh: |
    #!/bin/bash

    # Create topics "social-media-topic", "user-sentiment-topic", and "music-recommendation-topic"
    TOPICS=("social-media-topic" "user-sentiment-topic" "music-recommendation-topic")
    for TOPIC in "${TOPICS[@]}"; do
      /opt/bitnami/kafka/bin/kafka-topics.sh --create --topic "$TOPIC" --bootstrap-server "PLAINTEXT://${POD_NAME}.bitnami-kafka-headless.kafka-ns.svc.cluster.local:9092" --replication-factor 1 --partitions 3
      echo "Created topic: $TOPIC"
    done
